name: consul
description: Consul API for Dart
version: 0.0.1
repository: https://github.com/adaptant-labs/consul-dart
issue_tracker: https://github.com/adaptant-labs/consul-dart/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.13.5
  meta: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.22.2
